/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalautomatas;


import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Sams club
 */
public class Sintactico extends javax.swing.JFrame {

    /**
     * Creates new form Sintactico
     */
    public Sintactico() {
        initComponents();
        //this.setLocation(WIDTH, WIDTH);
        this.setLocation(450, 0);
        this.setSize(524,725);
        this.setResizable(false); 
    }
    static String BLOCK_COMMENT_PATTERN = "/\\*.*\\*/";
    static String COMMENT_PATTERN = "\\{(.*?)\\}";
    

   // public void setLocationRelativeTo(Component c) {
     //   super.setLocationRelativeTo(c); //To change body of generated methods, choose Tools | Templates.
        
    //}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // public void setLocationRelativeTo(Component c) {
    //   super.setLocationRelativeTo(c); //To change body of generated methods, choose Tools | Templates.
    //}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabla = new javax.swing.JDialog();
        btnAnalizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLexico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSintactico = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSemanticaCorrecta = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        tfSaltos = new javax.swing.JTextField();
        txtOpe = new javax.swing.JTextField();
        txtOper = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout TablaLayout = new javax.swing.GroupLayout(Tabla.getContentPane());
        Tabla.getContentPane().setLayout(TablaLayout);
        TablaLayout.setHorizontalGroup(
            TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        TablaLayout.setVerticalGroup(
            TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi_Lenguaje");
        getContentPane().setLayout(null);

        btnAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ANALZ.png"))); // NOI18N
        btnAnalizar.setBorderPainted(false);
        btnAnalizar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ANALZ1.png"))); // NOI18N
        btnAnalizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ANALZ1.png"))); // NOI18N
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnalizar);
        btnAnalizar.setBounds(280, 460, 100, 100);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LIMPIAR.png"))); // NOI18N
        btnLimpiar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LIMPIAR1.png"))); // NOI18N
        btnLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LIMPIAR1.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(390, 460, 100, 100);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente-boton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 570, 50, 30);

        txtLexico.setEditable(false);
        txtLexico.setColumns(20);
        txtLexico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtLexico.setRows(5);
        txtLexico.setEnabled(false);
        jScrollPane1.setViewportView(txtLexico);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 210, 70);

        txtSintactico.setEditable(false);
        txtSintactico.setColumns(20);
        txtSintactico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtSintactico.setRows(5);
        txtSintactico.setEnabled(false);
        jScrollPane2.setViewportView(txtSintactico);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 270, 210, 70);

        txtEntrada.setColumns(20);
        txtEntrada.setFont(new java.awt.Font("Arial", 3, 13)); // NOI18N
        txtEntrada.setRows(5);
        jScrollPane3.setViewportView(txtEntrada);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(280, 160, 200, 280);

        txtSemanticaCorrecta.setEditable(false);
        txtSemanticaCorrecta.setColumns(20);
        txtSemanticaCorrecta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtSemanticaCorrecta.setRows(5);
        txtSemanticaCorrecta.setEnabled(false);
        jScrollPane4.setViewportView(txtSemanticaCorrecta);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(40, 376, 210, 70);

        jScrollPane5.setEnabled(false);

        txtError.setColumns(20);
        txtError.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtError.setRows(5);
        txtError.setEnabled(false);
        jScrollPane5.setViewportView(txtError);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(40, 490, 210, 70);

        tfSaltos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tfSaltos.setEnabled(false);
        getContentPane().add(tfSaltos);
        tfSaltos.setBounds(160, 570, 300, 30);

        txtOpe.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtOpe.setEnabled(false);
        getContentPane().add(txtOpe);
        txtOpe.setBounds(160, 610, 350, 30);

        txtOper.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtOper.setEnabled(false);
        txtOper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOperActionPerformed(evt);
            }
        });
        getContentPane().add(txtOper);
        txtOper.setBounds(160, 650, 350, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenF.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 525, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        sintactico1 si = new sintactico1();
        si.Analizar();
        semantico se = new semantico();
        se.semantico();

        Pattern BLOCKCOMMENT_PATTERN_OBJ = Pattern.compile(BLOCK_COMMENT_PATTERN);
        Pattern IDENTIFIER_PATTERN_OBJ = Pattern.compile(COMMENT_PATTERN);

        Matcher BC_MATCHER = BLOCKCOMMENT_PATTERN_OBJ.matcher(txtEntrada.getText());
        Matcher ID_MATCHER = IDENTIFIER_PATTERN_OBJ.matcher(txtEntrada.getText());

        for (int i = 0; i < txtEntrada.getText().length(); i++) {
            if (BC_MATCHER.find()) {
                txtSintactico.append(BC_MATCHER.group());
               Sintactico.txtSemanticaCorrecta.append(BC_MATCHER.group());
            } else if (ID_MATCHER.find()) {
                txtSintactico.append(ID_MATCHER.group());
               Sintactico.txtSemanticaCorrecta.append(ID_MATCHER.group());
            }
        }
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtEntrada.setText("");
        txtLexico.setText("");
        txtSintactico.setText("");
    //    txtSemanticaCorrecta.setText("");
        txtError.setText("");
        txtSemanticaCorrecta.setText("");
        tfSaltos.setText("");
        txtOpe.setText("");
        txtOper.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtOperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOperActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        this.setLocation(0, 0);
        this.setSize(524,725);
        this.setResizable(false); 
        Tabla.setVisible(true);
        Tabla.setLocation(550, 0);
        Tabla.setSize(450,450);
        Tabla.setResizable(false); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sintactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sintactico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Tabla;
    public static javax.swing.JButton btnAnalizar;
    public static javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField tfSaltos;
    public static javax.swing.JTextArea txtEntrada;
    public static javax.swing.JTextArea txtError;
    public static javax.swing.JTextArea txtLexico;
    public static javax.swing.JTextField txtOpe;
    public static javax.swing.JTextField txtOper;
    public static javax.swing.JTextArea txtSemanticaCorrecta;
    public static javax.swing.JTextArea txtSintactico;
    // End of variables declaration//GEN-END:variables
}
